name: Python package

on:
  pull_request:
    branches:
      - main

env:
  DOMAIN: ${{ vars.TEST_DOMAIN }}
  SECRET_KEY_AUTH: ${{ vars.TEST_SECRET_KEY_AUTH }}
  SQL_DATABASE_URL: ${{ vars.TEST_SQL_DATABASE_URL }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdatabase
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          coverage run -m pytest test/
